name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What's happening?
      description: "Describe the bug in a few sentences."
      placeholder: "NPCs stop talking after fast traveling..."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "What were you doing when it happened? Any error messages or logs?"
      placeholder: "I fast traveled to Whiterun and tried talking to Lydia..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "What should happen instead?"
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: Game Version
      options:
        - SE (1.5.97)
        - AE (1.6.1170+)
        - VR
        - GOG
        - Other
    validations:
      required: true
  - type: input
    id: game-version-other
    attributes:
      label: Game Version (if Other)
      description: "If you selected Other above, specify your game version here."
      placeholder: "e.g. SE 1.5.80, Epic Games Store, etc."
    validations:
      required: false
  - type: input
    id: modlist
    attributes:
      label: Modlist
      description: "Which modlist are you using?"
      placeholder: "Lorerim, ADT, Wildlander, custom, etc."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SkyrimNet version
      placeholder: "beta16"
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: "Screenshots, log snippets, crash logs, etc."
    validations:
      required: false
